# Generated by Django 6.0.4 on 2026-04-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(choices=[('groq', 'Groq (LLaMA 3.3)'), ('hf_qwen', 'HuggingFace (Qwen 2.5)'), ('hf_gemma', 'HuggingFace (Gemma 2)')], default='groq', max_length=50),
        ),
    ]
